# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artículo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('foto', models.FileField(upload_to='')),
            ],
        ),
    ]
