# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artículo',
            new_name='Articulo',
        ),
    ]
