# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180111_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos_futbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('posicion', models.IntegerField()),
                ('puntos_torneo', models.IntegerField()),
                ('puntos_general', models.IntegerField()),
                ('p_jugados', models.IntegerField()),
                ('p_ganados', models.IntegerField()),
                ('p_empatados', models.IntegerField()),
                ('p_perdidos', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_contra', models.IntegerField()),
                ('dif_gol', models.IntegerField()),
            ],
        ),
    ]
