# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_equipos_futbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='dif_gol',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='goles_contra',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='goles_favor',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='p_empatados',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='p_ganados',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='p_jugados',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='p_perdidos',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='posicion',
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='dif_gol_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='dif_gol_torneo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='goles_contra_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='goles_contra_torneo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='goles_favor_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='goles_favor_torneo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='p_empatados_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='p_empatados_torneo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='p_ganados_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='p_ganados_torneo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='p_jugados_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='p_jugados_torneo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='p_perdidos_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='p_perdidos_torneo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='posicion_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipos_futbol',
            name='posicion_torneo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipos_futbol',
            name='puntos_general',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipos_futbol',
            name='puntos_torneo',
            field=models.IntegerField(default=0),
        ),
    ]
