# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180114_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='puntos_general',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol',
            name='puntos_torneo',
        ),
    ]
