# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180114_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos_futbol',
            old_name='posicion_general',
            new_name='puntos_general',
        ),
        migrations.RenameField(
            model_name='equipos_futbol',
            old_name='posicion_torneo',
            new_name='puntos_torneo',
        ),
    ]
