# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180115_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='foto',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
