# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20180203_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('Primera y Sub 21', 'Primera y Sub 21'), ('Inferiores', 'Inferiores'), ('Básquet', 'Básquet'), ('Hockey', 'Hockey'), ('Gurises', 'Gurises'), ('Generales', 'Generales'), ('Institucionales', 'Institucionales'), ('Senior', 'Senior')], max_length=200),
        ),
    ]
