# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20180204_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
