# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 00:37
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20180205_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=tinymce.models.HTMLField(),
        ),
    ]
