# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20180205_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
