# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_articulo_url_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='url_video',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
