# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20180213_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='album_facebook',
            field=models.CharField(blank=True, max_length=500, verbose_name='Inserte el link obtenido de Embed Social para compartir un álbum'),
        ),
    ]
