# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_articulo_album_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Ap_primera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Equipos_futbol_primera')),
            ],
        ),
    ]
