# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_tabla_ap_primera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('equipos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Equipos_futbol_primera')),
            ],
        ),
        migrations.RemoveField(
            model_name='tabla_ap_primera',
            name='equipos',
        ),
        migrations.DeleteModel(
            name='Tabla_Ap_primera',
        ),
    ]
