# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20180220_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablas',
            options={'ordering': ('nombre',)},
        ),
    ]
