# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20180220_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='dif_gol_general',
            field=models.IntegerField(default=0, verbose_name='DGG'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='dif_gol_torneo',
            field=models.IntegerField(default=0, verbose_name='DG'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='goles_contra_general',
            field=models.IntegerField(default=0, verbose_name='GCG'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='goles_contra_torneo',
            field=models.IntegerField(default=0, verbose_name='GC'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='goles_favor_general',
            field=models.IntegerField(default=0, verbose_name='GFG'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='goles_favor_torneo',
            field=models.IntegerField(default=0, verbose_name='GF'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='p_empatados_general',
            field=models.IntegerField(default=0, verbose_name='PEG'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='p_empatados_torneo',
            field=models.IntegerField(default=0, verbose_name='PE'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='p_ganados_general',
            field=models.IntegerField(default=0, verbose_name='PGG'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='p_ganados_torneo',
            field=models.IntegerField(default=0, verbose_name='PG'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='p_jugados_general',
            field=models.IntegerField(default=0, verbose_name='PJG'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='p_jugados_torneo',
            field=models.IntegerField(default=0, verbose_name='PJ'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='p_perdidos_general',
            field=models.IntegerField(default=0, verbose_name='PPG'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='p_perdidos_torneo',
            field=models.IntegerField(default=0, verbose_name='PP'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='puntos_general',
            field=models.IntegerField(default=0, verbose_name='Pts Gral'),
        ),
        migrations.AlterField(
            model_name='equipos_futbol_primera',
            name='puntos_torneo',
            field=models.IntegerField(default=0, verbose_name='Pts'),
        ),
    ]
