# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_auto_20180221_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='url_video',
            field=models.CharField(blank=True, help_text='Url del video de facebook (opcional). El link DEBE SER EMBED', max_length=500),
        ),
    ]
