# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20180221_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='url_video',
            field=models.CharField(blank=True, help_text='Url del video de facebook (opcional). Para obtener el link, ir al video, apretar donde están los 3 puntitos y poner "insertar". Pegar aquí solo el link del video, borrar el resto. Ejemplo: https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2FJuanCruzPiornoOficial%2Fvideos%2F302760100205413', max_length=500),
        ),
    ]
