# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20180221_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='album_facebook',
            field=models.CharField(blank=True, help_text="Ir al álbum de Facebook, apretar sobre los 3 puntitos y 'Obtener enlace'.Pegarlo acá", max_length=500),
        ),
    ]
