# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_auto_20180221_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posiciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0, verbose_name='Pts')),
                ('p_jugados', models.IntegerField(default=0, verbose_name='PJ')),
                ('p_ganados', models.IntegerField(default=0, verbose_name='PG')),
                ('p_empatados', models.IntegerField(default=0, verbose_name='PE')),
                ('p_perdidos', models.IntegerField(default=0, verbose_name='PP')),
                ('goles_favor', models.IntegerField(default=0, verbose_name='GF')),
                ('goles_contra', models.IntegerField(default=0, verbose_name='GC')),
                ('dif_gol', models.IntegerField(default=0, verbose_name='DG')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.RemoveField(
            model_name='tablas',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='dif_gol_general',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='dif_gol_torneo',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='goles_contra_general',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='goles_contra_torneo',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='goles_favor_general',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='goles_favor_torneo',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='p_empatados_general',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='p_empatados_torneo',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='p_ganados_general',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='p_ganados_torneo',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='p_jugados_general',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='p_jugados_torneo',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='p_perdidos_general',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='p_perdidos_torneo',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='puntos_general',
        ),
        migrations.RemoveField(
            model_name='equipos_futbol_primera',
            name='puntos_torneo',
        ),
        migrations.DeleteModel(
            name='Tablas',
        ),
        migrations.AddField(
            model_name='torneo',
            name='equipos',
            field=models.ManyToManyField(through='web.Posiciones', to='web.Equipos_futbol_primera'),
        ),
        migrations.AddField(
            model_name='posiciones',
            name='equipos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Equipos_futbol_primera'),
        ),
        migrations.AddField(
            model_name='posiciones',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Torneo'),
        ),
    ]
