# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20180221_1849'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipos',
            new_name='Equipo',
        ),
        migrations.RenameField(
            model_name='posiciones',
            old_name='equipos',
            new_name='equipo',
        ),
    ]
