# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20180222_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(help_text='Los nombres DEBEN SER (respetando comas y tildes) así: Primera, General Primera, Sub-21, General Sub-21, Sexta, Septima, Octava, Novena, General Inferiores', max_length=200),
        ),
    ]
