# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20180222_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='album_facebook',
        ),
        migrations.AddField(
            model_name='articulo',
            name='album_flickr',
            field=models.CharField(blank=True, help_text='Subir un álbum a Flickr, copiar enlace del álbum, ir a https://flickrembed.com/, generar el código y pegarlo acá', max_length=500),
        ),
    ]
