# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_auto_20180223_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='album_flickr',
            field=models.CharField(blank=True, help_text='Subir un álbum a Flickr, copiar enlace del álbum, ir a https://flickrembed.com/, generar el código y pegarlo acá', max_length=700),
        ),
    ]
