# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_auto_20180307_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='foto',
        ),
        migrations.AddField(
            model_name='articulo',
            name='url_foto',
            field=models.CharField(default='', help_text='Url de la imagen, previamente subida a FB u otro lugar', max_length=500),
        ),
    ]
