# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_auto_20180411_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='url_foto',
            field=models.CharField(default='', help_text='Url de la imagen, previamente subida a FB u otro lugar', max_length=1500),
        ),
    ]
