# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-11 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_auto_20180411_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='url_foto',
        ),
        migrations.AddField(
            model_name='articulo',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
